### ISSUE TITLE
[Request] BrainFuck Version

### ISSUE THREAD

**Issue by Mrgove10** [geohot/mergesorts#63]
I mean, is anyone crazy enough ?
This might help https://en.wikipedia.org/wiki/Brainfuck ... Good luck.

I know that there is [this version on github](https://github.com/hugopeixoto/mergesort/blob/master/brainfuck/mergesort.bf) but I have no clue how to convert it for this array....

**Comment by gshanbhag525** [comment]
@Mrgove10 Brainfuck ignores all characters except the eight commands +-<>[],.

**Comment by Mrgove10** [comment]
You should still be able to output characters

**Comment by gshanbhag525** [comment]
@Mrgove10 https://fatiherikli.github.io/brainfuck-visualizer/ This might help you. Also from line 7 to 17 in the github code u shared contain the array elements [10 , 9 , 8 ,  5 ,  6 , 7 , 4, 3 , 2 , 1].

**Comment by Mrgove10** [comment]
Thanks but i don't have the slightest bit of courage to event try 😂

**Comment by skooch** [comment]
https://github.com/geohot/mergesorts/pull/66
