### ISSUE TITLE
What is meant by "complexity"?

### ISSUE THREAD

**Issue by r-ba** [geohot/mergesorts#74]
> Our goal is to compare the length and "complexity" of the same code in many different languages. Which language is the best? Now we can know.

What is meant here by the "complexity" of code, and is it something that is well defined?

**Comment by 0xffset** [comment]
Maybe is referred to as a complex algorithm, that is defined as what fast or slow of a particular task of an algorithm performs.

**Comment by sytandas** [comment]
Amount of time or space required by an algorithm (usually input of given size of (n))

**Comment by r-ba** [comment]
@sayantan3 I'm aware of the theoretical definition. Each addition to this repository is an implementation of the same algorithm. The complexity of any algorithm is measured mathematically, which in and of itself has nothing to do with the language it's implemented in, the compiler used, or the architecture of the machine it's run on. 

The point is that the term "complexity" as used in the readme is loosely defined, and meaningless at worst.
